- name: Install dan jalankan NGINX
  hosts: test
  become: true
  tasks:
    - name: Install NGINX
      apt:
        name: nginx
        state: present
        update_cache: yes

    - name: Start dan enable NGINX
      service:
        name: nginx
        state: started
        enabled: yes
